// File generated by FlutterFire CLI.
// For more information, see: https://firebase.google.com/docs/cli/
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGEMRh41NW14TkgXC8uQ5SxfJaweCBnQI', // Replace with your actual Web API Key
    appId: '1:909042036334:android:741667641bf9b96267807f', // Replace with your actual Web App ID
    messagingSenderId: '909042036334', // Replace with your actual Messaging Sender ID
    projectId: '909042036334', // Replace with your actual Project ID
    authDomain: 'https://rumaan-ef5b4.firebaseapp.com/',
    storageBucket: 'your-firebase-project-id.appspot.com',
    measurementId: 'G-XXXXXXXXXX', // Optional: if you enabled Google Analytics
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGEMRh41NW14TkgXC8uQ5SxfJaweCBnQI', // Replace with your actual Android API Key
    appId: '1:909042036334:android:741667641bf9b96267807f', // Replace with your actual Android App ID
    messagingSenderId: '909042036334', // Replace with your actual Messaging Sender ID
    projectId: 'rumaan-ef5b4', // Replace with your actual Project ID
    storageBucket: 'rumaan-ef5b4.firebasestorage.app',
  );

 
}
